version: "3.7"
services:
  magiclistapp:
    build:
      args:
        user: victor
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: victormaderaa/magiclist
    container_name: magiclist-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - volmagiclist:/var/www/

networks:
  default:
    external:
      name: server_network

volumes:
  volmagiclist: